name: Sync to Rohan's Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone original repository
        run: |
          git clone https://github.com/devnath-p/PiePoint.git repo
          cd repo

          git remote add backup https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/RohanRam/PiePoint.git

          git fetch --all --tags
          git push backup --all --force
          git push backup --tags --force
